# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 100

# Add only the root, not each workspace item
# https://github.com/dependabot/dependabot-core/issues/4993#issuecomment-1289133027
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  # PNPM has an issue with dependabot. See:
  # https://github.com/dependabot/dependabot-core/issues/7258
  # https://github.com/pnpm/pnpm/issues/6530
  # TODO: Restore this when the issue is solved
  open-pull-requests-limit: 0
  groups:
    swc:
      patterns:
        - "@swc/*"
    storybook:
      patterns:
        - "storybook*"
        - "@storybook/*"
