name: ✨ Feature Request
description: Suggest an idea for this project
labels: ["✨Feature"]

body:
  - type: textarea
    attributes:
      label: Summary
      description: Tell us what the suggestion is
    validations:
      required: true
