url: 'http://misskey.local'

# ローカルでテストするときにポートを被らないようにするためデフォルトのものとは変える(以下同じ)
port: 61812

db:
  host: 127.0.0.1
  port: 54312
  db: test-misskey
  user: postgres
  pass: ''
redis:
  host: 127.0.0.1
  port: 56312
id: aidx
