name: Publish Docker image (develop)

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: github.repository == 'misskey-dev/misskey'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.6.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.9.1
        with:
          platforms: linux/amd64,linux/arm64
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: misskey/misskey
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          push: true
          platforms: ${{ steps.buildx.outputs.platforms }}
          provenance: false
          tags: misskey/misskey:develop
          labels: develop
          cache-from: type=gha
          cache-to: type=gha,mode=max
