name: Publish Docker image (develop)

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  push_to_registry:
    name: Push Docker image to GHCR
    runs-on: ubuntu-latest
    if: github.repository == 'transfem-org/Sharkey'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.0.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0
        with:
          platforms: linux/amd64
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: transfem-org/Sharkey
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to GHCR
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          push: true
          platforms: ${{ steps.buildx.outputs.platforms }}
          provenance: false
          tags: transfem-org/Sharkey:develop
          labels: develop
          cache-from: type=gha
          cache-to: type=gha,mode=max
